<a href="https://colab.research.google.com/github/brien60/Stock-LSTM/blob/SLOT/SLOT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Setup

### Imports

In [133]:
import torch
from torch import nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

from pathlib import Path
import json
import re

import sentencepiece as sp
from collections import Counter

import pandas as pd

from tqdm import tqdm

### Colab Setup Code

In [2]:
!git clone --branch SLOT https://github.com/brien60/Stock-LSTM.git
%cd Stock-LSTM/
!unzip -q data.zip -d /content/Stock-LSTM/data

Cloning into 'Stock-LSTM'...
remote: Enumerating objects: 159, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 159 (delta 5), reused 9 (delta 2), pack-reused 140 (from 2)
Receiving objects: 100% (159/159), 140.76 MiB | 14.97 MiB/s, done.
Resolving deltas: 100% (53/53), done.
Updating files: 100% (19/19), done.
/content/Stock-LSTM

### Constants

In [ ]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)
device = "cuda" if torch.cuda.is_available() else "cpu"


dataset = "acl18"
dataset_dir = Path(dataset.upper())

data_dir = Path(f"data/{dataset}")

tweet_dir = data_dir / "tweet"
price_dir = data_dir / "price"

tweet_files_list = list(tweet_dir.rglob("*/*"))
list.sort(tweet_files_list)

json_file = dataset_dir / "all_tweets.jsonl"
spm_file = dataset_dir / "spm/slot_tweet_spm.model"
tokens_file = dataset_dir / "all_tweets_tokenized.jsonl"


vocab_size = 10_000

window_size = 10

## SLOT Overview

SLOT (Self-supervised Learning of Tweets for Capturing Multi-level Price Trends) aims to address
1. the sparsity of tweets, with the number of tweets being heavily biased towards the most popular stocks.
2. the fact that tweets have noisy information that are often irrelevant to the actual stock movement.

The first problem was addressed by having SLOT learn the stock and tweet embeddings in the same vector space through self-supervised learning. This allows the use of any tweet for even unpopular stocks.

To tackle the second problem, SLOT uses tweets to learn multi-level relationships between stocks, rather than using them as direct evidence for stock prediction (e.g. positive sentiment = up).

## Attention LSTM

In [ ]:

class ALSTM(nn.Module):
    def __init__(self, input_size, hidden_size):
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            batch_first=True,
        )
        self.ln = nn.Linear(hidden_size, hidden_size)
        self.tanh = nn.Tanh()
        self.u = nn.Parameter(data=torch.randn(hidden_size))


    def forward(self, x):
        # x: (batch, seq_len, input_size)
        # output: (batch, seq_len, hidden_size)
        # h_n, c_n : (num_layers, batch, hidden_size)
        output, h_n, c_n = self.lstm(x)
        output = self.tanh(self.ln(output))

        # query: u, key: output, values: output
        attn_scores = torch.matmul(output, self.u) # (batch, seq_len, hidden_size) @ (hidden_size) -> (batch, seq_len)
        weights = attn_scores / attn_scores.sum(dim=1, keepdim=True)
        weights = weights.unsqueeze(dim=-1) # (batch, seq_len, 1)

        # (batch, seq_len, 1) * (batch, seq_len, hidden_size) -> (batch, seq_len, hidden_size)
        # (batch, seq_len, hidden_size) -> (batch, hidden_size)
        h_attn = (weights * output).sum(dim=1)

        # (batch, hidden_size) || (batch, hidden_size) -> (batch, 2*hidden_size)
        h_out = torch.cat((h_n[0], h_attn), dim=1) # both the general summary and the attention

        return h_out

In [ ]:
class SLOT(nn.Module):
    def __init__(self, input_size, hidden_size, output_size = 1):
        self.ln_1 = nn.Linear(3*input_size, 3*input_size)
        self.alstm = ALSTM(input_size=3*input_size, hidden_size=hidden_size)
        self.ln_f = nn.Linear(hidden_size*2, output_size)

    def forward(self, features, global_trend, local_trend):
        # features, global_trend, local_trend: (batch, seq_len, input_size)
        final_input = torch.cat((features, global_trend, local_trend), dim=-1) # (batch, 3*input_size)
        final_input = self.ln_1(final_input)
        h_out = self.alstm(final_input) # (batch, 2*hidden_size)
        y_pred = self.ln_f(h_out) # (batch, output_size)

        return y_pred

## Price Features

The price features that compose a feature vector $x_{st}$ are
- Price movements in a day: *c_open, c_high, c_low*
- Price movements between days: *n_close, n_adj_close*
- Long-term movements: *5_day, 10_day, ... , 30_day*

So the daily prices of days $t-29$ to $t$ are used to generate each $x_{st}$

These features have already been calculated and normalized in the csv files.

### Extracting features data

In [187]:
data_files_list = list(price_dir.rglob("*.csv"))

data_list = []

price_features = []
labels = []

for i, stock_file in enumerate(data_files_list):
    stock = stock_file.stem
    df = pd.read_csv(stock_file)
    # columns = [
    #     f'{stock}_c_open', f'{stock}_c_high', f'{stock}_c_low',
    #     f'{stock}_n_close', f'{stock}_n_adj_close',
    #     f'{stock}_adj_sum_5', f'{stock}_adj_sum_10', f'{stock}_adj_sum_15',
    #     f'{stock}_adj_sum_20', f'{stock}_adj_sum_25', f'{stock}_adj_sum_30',
    #     f'{stock}_label', f'{stock}_closing_price_for_label'
    # ]

    # price_features.extend(columns[:-2])
    # labels.append(columns[-2])
    
    # if i != 0: 
    # df.drop(columns=['date'], inplace=True)
    # else:
        # columns = ['date'] + columns

    # df.columns = columns

    df['label'] = df['label'].shift(-1)
    df = df.dropna()

    data_list.append(df)

# combined_df = pd.concat(data_list, axis=1)
# combined_df = combined_df.dropna()

# combined_df
data_list[0]

,date,c_open,c_high,c_low,n_close,n_adj_close,adj_sum_5,adj_sum_10,adj_sum_15,adj_sum_20,adj_sum_25,adj_sum_30,label,closing_price_for_label
0,2013-06-03,0.002215,0.363858,-1.828186,0.220128,0.220127,-0.673593,-1.276852,-1.713707,-0.949655,-1.295995,-2.789459,0.0,59.171677
1,2013-06-04,0.870223,1.139527,-0.427319,-0.312838,-0.312846,-0.011565,-0.825038,-1.485826,-0.731958,-0.790216,-2.089251,-1.0,58.986561
2,2013-06-05,0.121322,1.260365,-0.314531,-0.934764,-0.934782,0.939114,0.233220,-0.537524,0.086406,0.193033,-0.853451,-1.0,58.435165
3,2013-06-06,1.598781,1.947728,-1.005795,-1.494014,-1.493998,1.871554,1.687500,1.117097,1.349731,1.731397,0.921408,1.0,57.562145
4,2013-06-07,-1.201875,0.323667,-2.046127,0.764040,0.764051,0.740579,0.908979,0.459466,0.411936,0.952945,0.428645,-1.0,58.001949
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,2015-12-23,-1.233776,0.220971,-1.298227,1.286951,1.286929,-0.896777,1.449230,3.624597,4.776731,5.624166,5.576534,-1.0,104.940506
647,2015-12-24,0.897900,0.897900,-0.074055,-0.534023,-0.534011,-0.540592,1.240396,3.738465,4.876420,5.848372,5.894038,-1.0,104.380112
648,2015-12-28,0.720835,0.814456,-0.599139,-1.120058,-1.120053,0.733942,1.791792,4.151524,5.549981,6.599504,6.815818,1.0,103.210999
649,2015-12-29,-1.636931,0.634543,-1.728892,1.797414,1.797402,-0.785352,-0.349452,1.727675,3.246740,4.328862,4.819452,-1.0,105.066116
650,2015-12-30,1.174061,1.285871,-0.130451,-1.305865,-1.305853,0.544159,0.673679,2.395942,4.146003,5.320527,5.993281,-1.0,103.694107

In [188]:
for df in data_list:
    df.drop(columns=['date'], inplace=True)

data_list[0]

,c_open,c_high,c_low,n_close,n_adj_close,adj_sum_5,adj_sum_10,adj_sum_15,adj_sum_20,adj_sum_25,adj_sum_30,label,closing_price_for_label
0,0.002215,0.363858,-1.828186,0.220128,0.220127,-0.673593,-1.276852,-1.713707,-0.949655,-1.295995,-2.789459,0.0,59.171677
1,0.870223,1.139527,-0.427319,-0.312838,-0.312846,-0.011565,-0.825038,-1.485826,-0.731958,-0.790216,-2.089251,-1.0,58.986561
2,0.121322,1.260365,-0.314531,-0.934764,-0.934782,0.939114,0.233220,-0.537524,0.086406,0.193033,-0.853451,-1.0,58.435165
3,1.598781,1.947728,-1.005795,-1.494014,-1.493998,1.871554,1.687500,1.117097,1.349731,1.731397,0.921408,1.0,57.562145
4,-1.201875,0.323667,-2.046127,0.764040,0.764051,0.740579,0.908979,0.459466,0.411936,0.952945,0.428645,-1.0,58.001949
...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,-1.233776,0.220971,-1.298227,1.286951,1.286929,-0.896777,1.449230,3.624597,4.776731,5.624166,5.576534,-1.0,104.940506
647,0.897900,0.897900,-0.074055,-0.534023,-0.534011,-0.540592,1.240396,3.738465,4.876420,5.848372,5.894038,-1.0,104.380112
648,0.720835,0.814456,-0.599139,-1.120058,-1.120053,0.733942,1.791792,4.151524,5.549981,6.599504,6.815818,1.0,103.210999
649,-1.636931,0.634543,-1.728892,1.797414,1.797402,-0.785352,-0.349452,1.727675,3.246740,4.328862,4.819452,-1.0,105.066116
650,1.174061,1.285871,-0.130451,-1.305865,-1.305853,0.544159,0.673679,2.395942,4.146003,5.320527,5.993281,-1.0,103.694107

In [189]:
columns = data_list[0].columns.to_list()
price_features = columns[: -2]
labels = columns[-2]

In [208]:
X_st = [
    torch.tensor(df[price_features].to_numpy(), dtype=torch.float)
    for df in data_list
]
y = [
    torch.tensor(df[labels].to_numpy(), dtype=torch.float)
    for df in data_list
]

X_st = torch.stack(X_st).transpose(0, 1)
y = torch.stack(y).transpose(0, 1)

X_st[0, :5], X_st.shape, y, y.shape

(tensor([[ 2.2150e-03,  3.6386e-01, -1.8282e+00,  2.2013e-01,  2.2013e-01,
          -6.7359e-01, -1.2769e+00, -1.7137e+00, -9.4965e-01, -1.2960e+00,
          -2.7895e+00],
         [-9.9412e-01,  1.3557e-01, -1.3556e+00,  1.5603e+00,  1.5603e+00,
          -2.3497e-01,  2.6209e-01,  2.8017e-01,  9.4443e-01,  1.0650e+00,
           4.2217e-01],
         [-1.1070e+00,  5.0738e-01, -1.4068e+00,  1.5695e+00,  1.5695e+00,
           1.4160e+00,  4.1190e+00,  4.6679e+00,  4.1282e+00,  4.1052e+00,
           3.9545e+00],
         [-7.3689e-01,  3.6845e-01, -2.4274e+00,  6.9838e-01,  6.9839e-01,
           4.3340e-02,  2.7763e+00,  4.0095e+00,  4.9172e+00,  5.9330e+00,
           6.3949e+00],
         [-1.2332e+05, -1.2332e+05, -1.2332e+05, -1.2332e+05, -1.2332e+05,
          -1.2332e+05, -1.2332e+05, -1.2332e+05, -1.2332e+05, -1.2332e+05,
          -1.2332e+05]]),
 torch.Size([651, 87, 11]),
 tensor([[ 0.,  0.,  1.,  ..., -1.,  0., -1.],
         [-1., -1., -1.,  ..., -1., -1., -1.],
         [-1.,  1.,  1.,  ...,  1.,  0.,  1.],
         ...,
         [ 1.,  0.,  1.,  ...,  1.,  1.,  0.],
         [-1., -1.,  1.,  ..., -1.,  0., -1.],
         [-1., -1., -1.,  ..., -1., -1.,  0.]]),
 torch.Size([651, 87]))

### Multi-level feature

In [ ]:
class Multi_Level_Feature(nn.Module):
    def __init__(self, input_size):
        # input size is the size of each feature
        self.ln = nn.Linear(3*input_size, 3*input_size)

    def forward(self, features, global_trend, local_trend):
        # features, global_trend, local_trend: (seq_len, input_size)
        final_input = torch.cat((features, global_trend, local_trend)) # (seq_len, 3*input_size)
        final_input = self.ln(final_input)

        return final_input

### Windows

In [ ]:
num_windows = len(combined_df) - window_size

In [ ]:
# input: batch_size, window_size, price features for all stocks in that time window
# labels: labels for all stocks at time t

## Self-supervised Learning of Embeddings

The goal is to learn tweet (h_e) and stock (h_s) embeddings in the same semantic space, that is, learning the embeddings together such that one embedding can be used to query for the other.
- a stock embedding and the embedding of tweet relevant to it are close together (higher dot product)
- stocks that are frequently co-mentioned will have similar embeddings; this naturally groups together stocks in the same industry/sector.
- solves problem of tweet sparsity; the model can associate stocks with tweets that don't directly mention it as long as they are close in vector space.

This was done by training for stock identification: predict the mentioned stock in a tweet when the stock symbol is masked.

Every tweet is tokenized with Sentence Piece and then the tokens that correspond to the stock the tweet mentions are masked with the special token MASK.
- "Thank you Apple for the new iPhone." -> "Thank you [MASK] for the new iPhone."

### Stock Identification Model

Use a BiLSTM (need to understand the context on both sides of the mask token).
- Using a transformer risks overfitting.

The stock embedding is a learnable parameter.

The hidden state vector generated at the masked token is used as the tweet embedding because it
- captures the immediate left (via the forward LSTM) and right context (via the backward LSTM) of the tweet, making it exactly what we need for stock identification,
- and it is the part of the tweet that most connects to mentioned stock.

### Write raw data to json

In [ ]:

buffer = []
buffer_size = 100_000
lines = 0

with open(json_file, "w", encoding="utf-8") as out:
    for tweet_file in tweet_files_list:
        
        with open(tweet_file, "r", encoding="utf-8") as f:
            

            for line in f:
                tweet = json.loads(line)

                json_tweet = {
                    "date": tweet_file.stem,
                    "stock": tweet_file.parent.name,
                    "tweet": tweet["text"].replace("\n", " ")
                }

                buffer.append(json.dumps(json_tweet))

                if len(buffer) >= buffer_size:
                    out.write("\n".join(buffer) + "\n")
                    lines += len(buffer)

                    buffer.clear()

                    print(f"{lines} lines written")

    if buffer:
        lines += len(buffer)
        out.write("\n".join(buffer) + "\n")
        print(f"{lines} lines written")

print("All tweets written")

100000 lines written
119844 lines written
All tweets written

### Txt file for sp training

In [62]:
input_file = json_file
output_file = dataset_dir / "tweets_for_sp.txt"

with open(input_file, "r", encoding="utf-8") as f, open(output_file, "w", encoding="utf-8") as out:
    for line in f:
        tweet = json.loads(line)
        out.write(tweet["tweet"] + "\n")

### SPM Training

In [ ]:
spm_file = dataset_dir / "spm/slot_tweet_spm"
vocab_size = 10_000

sp.SentencePieceTrainer.train(
    input=output_file,
    model_prefix=spm_file,
    vocab_size=vocab_size,
    model_type="unigram",
    character_coverage=1.0,
    input_sentence_size=lines,
    shuffle_input_sentence=True,
    user_defined_symbols=["<MASK>", "<PAD>", "<UNK>"]
)

spm_file = str(spm_file.with_suffix(".model"))

In [3]:
slot_spm = sp.SentencePieceProcessor()
slot_spm.load(str(spm_file))

mask_id = slot_spm.piece_to_id("<MASK>")
pad_id = slot_spm.piece_to_id("<PAD>")
unk_id = slot_spm.piece_to_id("<UNK>")

mask_id, pad_id, unk_id

(3, 4, 5)

In [5]:
all_token_ids = []

with open(json_file, "r", encoding="utf-8") as f:
    for line in f:

        entry = json.loads(line)

        tweet = entry["tweet"]

        tweet_tokenized = slot_spm.encode(tweet)

        all_token_ids.extend(tweet_tokenized)

token_counts = Counter(all_token_ids)

rare_tokens = [tok for tok, freq in token_counts.items() if freq < 3]
len(rare_tokens)

888

In [ ]:
for tok in rare_tokens:
    print(slot_spm.id_to_piece(tok))

既
然
说
那
就
真
🐂
蹦
‘


›
⤴
ą
⇓
⬆
غ
线
门
件
对
响
似
乎
位
震
荡
😯
💶
💷
٨
؟
☯
±
😀
次
四
半
獄
度
離
点
損
〜
方
弱
落
可
虑
抛
⌚
🏝
🎯
ő
🔵
⁂
✡
ゾ
表
⛄
🌚
😬
🌱
ᄉ
づ
👶
🎣
马
云
英
文
讲
钟
征
服
德
国
怎
么
刷
脸
支
付
秒
左
右
开
始
✳
含
相
偏
差
🅱
🎹
🎻
🎸
🎷
🎺
📹
📀







🍷
γ
解
✘
❝
❞
➕
🔔
🔱
✅
💿
部
曽
根
商
街
ׄ
׿
ț
ұ
め
ぃ
質
問
岐
阜
ベ
動
画
丈
夫
客
邪
魔
迷
致
願
写
後
ぶ
塾
物
帰
ゲ
寄
🔴
🏈
条
式
書
ぜ
矢
仕
更
🆑
土
庄
内
緑
園
海
少
女
取
急
編
集
速
版
続
ぁ
長
谷
川
宮
穫
👬
🚣
😕
🏇
外
爆
黒
田
酷
崎
洋
泣
虫
夲
鮓
第
判
橸
邂
牢
噂
具
豸
訷
荳
牙
讖
即
革
使
■
京

ժ
׎
녕
친
和
≥
↕
⇄
😐
👳
反
転
進
曲
載
形
対
応
닷
컴
가
唐
突
予
約
じ
夏
届
勿
論
金
曜
華
受
🚬

並
ヂ




梯
蚪
侠
ゥ
羅
爨


ヌ
鑅

翅
毋
⚽
🚢
🚍
🌜
🏄
ĥ
📶
코
감
기
테
팅
못
겟
와
타
램
술
👔
家
兄
ザ
덛
պ
꿸
ۏ
ʥ
֕
ȩ
開
😓
🔪
級
描
夢
濃
縮
作
🌸
💠
🌑
🙅
🌅
ヒ
🔃
🍄
🍂
🍃
🐛
🌠
🆙
🐸
☕
🔂
☁
̧
☠
🌌
🍇
♿
🚰
🚹
🅿
🍯
👨
隆
臣
🔞
🎃
👲
🎡
🎨
🎆
🌃
💆
譁
扇
名
ミ
蜀
拘
呵
郞
霆
幟
垂
🎮
😮
😝
👿
😚
💝
🎌
📫
🌡
➰
太
赞
잉
여
들
좀
더
노
력
페
북
을
추
월
것
도
록
합
시
⛔
📬
📁
ग
ल
ट
ब
ू
च
ो
क
ि
ड
स
🐣
稚
痴

¬

🐟
法
通
电
气
并
购
阿
尔
斯
igx
品
鉄
道
原
油
格
悪
響
将
刀
价
还
如
果
能
拆
元
有
信
奉
司
成
东
应
该
等
跌
压
惊
存
个
三
待
繋
頭
花
畑
비
―
↡
🚧
➲
休
個
別
伴
展
望
末
雇
統
計
拠
検
証
採
過
去
昔
自
売
言
祝
世
界
员
福
健
康
平
顺
利
leaps
⌛
巴
伦
氏
周
刊
这
篇
析
被
种
转
载
打
深
企
业
况
⤋
🐋
温
暖
化
排
量
削
減
😨
私
ฯ
ษ
ธ
โ
友
達
代
聞
〽
警
備
員
面
◆
◇



☑
🐪
🐔
🔯
👻
◉
∃
╮
╯
╰
╭
번
주
말
씨
용
불
량
자
출
현
항
조
씩
필
한
만
큼
결
욧
앞
으
계
속
연
락
부
탁
讎
戯
繧
螂
杣
豐
髱
朱
勁
費
稲
醗
逾
評
ถ
ึ
ᗯ
ᑭ
ᖴ
ᐯ
⇨
⇦
본
활
형
룹
저
희
무
했
습
많
봐
๋
ṡ
ģ

ż
🚄
❀
ღ
∅
∈
👭
🍰

ǥ
ɨ
🎊
♑
♊
☹
庭
ハ
虔
潭
伝
構
何
沙
耶
唄
☔
🌞
🔝
🍹
嫌
🍭
🍕
❓
🙉
🙊
供
詳
細
回
◎
懐
録
ǧ
ώ
ǝ
➳
좋
은
곳
▷
💍
ざ
せ
💓
ョ
📷
素
敵
᙭
ᑕ
ѕ
ĸ
♣
🍸
ỗ
ấ
ớ
ự
ễ
ợ
👼
담
청
님
라
키
토
료
려
립
바
멘
션
🍳
💑
🔹
🔸
즘
올
림
픽
컵
할
배
평
균
접
명
천
운
🏀
○
์
🗽
🌉
ō
🍔
🍟
👫
‡
✩
⑅
◡
⃝
🔽
⌒
▽
🐝
学
紹
介
主
催
参
加
非
覧
魅
力
ㄣ
⃒
💛
╺
͡
͜
ʖ
⋮
ᕁ
󾮟
󾦃
󾁇
宇
宙
蛍
詩
梨
歌
󾭻
󾬥
󾦈
󾒰
🚎
祭
初
援
頑
張
🍼
🎀
ĝ
❾
🌵
ś
ć
岸
ヘ
古
者
ぱ
晩
流
晴
彦
🍗
┳

⚫
󾍛
󾓑
󾓠
👙
😟
📍
🤑
📸
🖖
弾
語
👄
般
若
治
俺
漢
μ
╣
ȋ
ə
ʀ
✒
🛩
🏁
難
波
井
む
拡
熱
柊
堕
餅
早
乙
麗
📞
뉴
넷
간
베
편
업
데
곰
렌
음
작
유
럽
거
내
성
애
섹
告
知
盤
合
🤔
態
🐾
🎄
🐡
ฬ
ן
列
疲
仲
👪
🔐
👓
😾
󾦄
󾁃
󾁎
󾠡
󾠔
󾠁
ҍ
ϼ
百
万
刈
立
城
ギ
厳
選
ʾ
ύ
ԧ
ϫ
¦

🚮


### Create tokenized jsonl

In [6]:
all_dates = []

for tweet_file in tweet_files_list:
        date = tweet_file.stem
        all_dates.append(date)


all_dates = sorted(dict.fromkeys(all_dates))

start_date, end_date = "2014-01-02", "2015-12-30"
start_date_idx, end_date_idx = all_dates.index(start_date), all_dates.index(end_date)

all_dates = all_dates[start_date_idx : end_date_idx + 1]
all_dates

['2014-01-02',
 '2014-01-03',
 '2014-01-04',
 '2014-01-05',
 '2014-01-06',
 '2014-01-07',
 '2014-01-08',
 '2014-01-09',
 '2014-01-10',
 '2014-01-11',
 '2014-01-12',
 '2014-01-13',
 '2014-01-14',
 '2014-01-15',
 '2014-01-16',
 '2014-01-19',
 '2014-01-20',
 '2014-01-21',
 '2014-01-22',
 '2014-01-23',
 '2014-01-24',
 '2014-01-25',
 '2014-01-26',
 '2014-01-27',
 '2014-01-28',
 '2014-01-29',
 '2014-01-30',
 '2014-01-31',
 '2014-02-01',
 '2014-02-02',
 '2014-02-03',
 '2014-02-04',
 '2014-02-05',
 '2014-02-06',
 '2014-02-07',
 '2014-02-08',
 '2014-02-09',
 '2014-02-10',
 '2014-02-11',
 '2014-02-12',
 '2014-02-13',
 '2014-02-14',
 '2014-02-15',
 '2014-02-16',
 '2014-02-17',
 '2014-02-18',
 '2014-02-19',
 '2014-02-20',
 '2014-02-21',
 '2014-02-22',
 '2014-02-23',
 '2014-02-24',
 '2014-02-25',
 '2014-02-26',
 '2014-02-27',
 '2014-02-28',
 '2014-03-01',
 '2014-03-02',
 '2014-03-03',
 '2014-03-04',
 '2014-03-05',
 '2014-03-06',
 '2014-03-07',
 '2014-03-08',
 '2014-03-09',
 '2014-03-10',
 '2014-03-11',
 '2014-03-12',
 '2014-03-13',
 '2014-03-14',
 '2014-03-15',
 '2014-03-16',
 '2014-03-17',
 '2014-03-18',
 '2014-03-19',
 '2014-03-20',
 '2014-03-21',
 '2014-03-22',
 '2014-03-23',
 '2014-03-24',
 '2014-03-25',
 '2014-03-26',
 '2014-03-27',
 '2014-03-28',
 '2014-03-29',
 '2014-03-30',
 '2014-03-31',
 '2014-04-01',
 '2014-04-02',
 '2014-04-03',
 '2014-04-04',
 '2014-04-05',
 '2014-04-06',
 '2014-04-07',
 '2014-04-08',
 '2014-04-09',
 '2014-04-10',
 '2014-04-11',
 '2014-04-12',
 '2014-04-13',
 '2014-04-14',
 '2014-04-15',
 '2014-04-16',
 '2014-04-17',
 '2014-04-18',
 '2014-04-19',
 '2014-04-20',
 '2014-04-21',
 '2014-04-22',
 '2014-04-23',
 '2014-04-24',
 '2014-04-25',
 '2014-04-26',
 '2014-04-27',
 '2014-04-28',
 '2014-04-29',
 '2014-04-30',
 '2014-05-01',
 '2014-05-02',
 '2014-05-03',
 '2014-05-04',
 '2014-05-05',
 '2014-05-06',
 '2014-05-07',
 '2014-05-08',
 '2014-05-09',
 '2014-05-10',
 '2014-05-11',
 '2014-05-12',
 '2014-05-13',
 '2014-05-14',
 '2014-05-15',
 '2014-05-16',
 '2014-05-17',
 '2014-05-18',
 '2014-05-19',
 '2014-05-20',
 '2014-05-21',
 '2014-05-22',
 '2014-05-23',
 '2014-05-24',
 '2014-05-25',
 '2014-05-26',
 '2014-05-27',
 '2014-05-28',
 '2014-05-29',
 '2014-05-30',
 '2014-05-31',
 '2014-06-01',
 '2014-06-02',
 '2014-06-03',
 '2014-06-04',
 '2014-06-05',
 '2014-06-06',
 '2014-06-07',
 '2014-06-08',
 '2014-06-09',
 '2014-06-10',
 '2014-06-11',
 '2014-06-12',
 '2014-06-13',
 '2014-06-14',
 '2014-06-15',
 '2014-06-16',
 '2014-06-18',
 '2014-06-19',
 '2014-06-20',
 '2014-06-21',
 '2014-06-22',
 '2014-06-23',
 '2014-06-24',
 '2014-06-25',
 '2014-06-26',
 '2014-06-27',
 '2014-06-28',
 '2014-06-29',
 '2014-06-30',
 '2014-07-01',
 '2014-07-02',
 '2014-07-03',
 '2014-07-04',
 '2014-07-05',
 '2014-07-06',
 '2014-07-07',
 '2014-07-08',
 '2014-07-09',
 '2014-07-10',
 '2014-07-11',
 '2014-07-12',
 '2014-07-13',
 '2014-07-14',
 '2014-07-15',
 '2014-07-16',
 '2014-07-17',
 '2014-07-18',
 '2014-07-19',
 '2014-07-20',
 '2014-07-21',
 '2014-07-22',
 '2014-07-23',
 '2014-07-24',
 '2014-07-25',
 '2014-07-26',
 '2014-07-27',
 '2014-07-28',
 '2014-07-29',
 '2014-07-30',
 '2014-07-31',
 '2014-08-01',
 '2014-08-02',
 '2014-08-03',
 '2014-08-04',
 '2014-08-05',
 '2014-08-07',
 '2014-08-08',
 '2014-08-09',
 '2014-08-10',
 '2014-08-11',
 '2014-08-12',
 '2014-08-13',
 '2014-08-14',
 '2014-08-15',
 '2014-08-16',
 '2014-08-17',
 '2014-08-18',
 '2014-08-19',
 '2014-08-20',
 '2014-08-21',
 '2014-08-22',
 '2014-08-23',
 '2014-08-24',
 '2014-08-25',
 '2014-08-26',
 '2014-08-27',
 '2014-08-28',
 '2014-08-29',
 '2014-08-30',
 '2014-08-31',
 '2014-09-01',
 '2014-09-02',
 '2014-09-03',
 '2014-09-04',
 '2014-09-05',
 '2014-09-06',
 '2014-09-07',
 '2014-09-08',
 '2014-09-09',
 '2014-09-10',
 '2014-09-11',
 '2014-09-12',
 '2014-09-13',
 '2014-09-14',
 '2014-09-15',
 '2014-09-16',
 '2014-09-17',
 '2014-09-18',
 '2014-09-19',
 '2014-09-20',
 '2014-09-21',
 '2014-09-22',
 '2014-09-23',
 '2014-09-29',
 '2014-09-30',
 '2014-10-01',
 '2014-10-02',
 '2014-10-03',
 '2014-10-04',
 '2014-10-05',
 '2014-10-06',
 '2014-10-07',
 '2014-10-08',
 '2014-10-09',
 '2014-10-10',
 '2014-10-11',
 '2014-10-12',
 '2014-10-13',
 '2014-10-14',
 '2014-10-15',
 '2014-10-16',
 '2014-10-17',
 '2014-10-18',
 '2014-10-19',
 '2014-10-20',
 '2014-10-21',
 '2014-10-22',
 '2014-10-23',
 '2014-10-24',
 '2014-10-25',
 '2014-10-26',
 '2014-10-27',
 '2014-10-28',
 '2014-10-29',
 '2014-10-30',
 '2014-10-31',
 '2014-11-01',
 '2014-11-02',
 '2014-11-03',
 '2014-11-04',
 '2014-11-05',
 '2014-11-06',
 '2014-11-07',
 '2014-11-08',
 '2014-11-09',
 '2014-11-14',
 '2014-11-23',
 '2014-11-24',
 '2014-11-25',
 '2014-11-26',
 '2014-11-27',
 '2014-11-28',
 '2014-11-29',
 '2014-11-30',
 '2014-12-01',
 '2014-12-02',
 '2014-12-03',
 '2014-12-04',
 '2014-12-05',
 '2014-12-06',
 '2014-12-07',
 '2014-12-08',
 '2014-12-09',
 '2014-12-10',
 '2014-12-11',
 '2014-12-12',
 '2014-12-13',
 '2014-12-14',
 '2014-12-15',
 '2014-12-16',
 '2014-12-17',
 '2014-12-18',
 '2014-12-19',
 '2014-12-21',
 '2014-12-22',
 '2014-12-23',
 '2014-12-24',
 '2014-12-25',
 '2014-12-26',
 '2014-12-27',
 '2014-12-28',
 '2014-12-29',
 '2014-12-30',
 '2014-12-31',
 '2015-01-01',
 '2015-01-02',
 '2015-01-03',
 '2015-01-04',
 '2015-01-05',
 '2015-01-06',
 '2015-01-07',
 '2015-01-08',
 '2015-01-09',
 '2015-01-10',
 '2015-01-11',
 '2015-01-12',
 '2015-01-13',
 '2015-01-14',
 '2015-01-15',
 '2015-01-16',
 '2015-01-17',
 '2015-01-18',
 '2015-01-19',
 '2015-01-20',
 '2015-01-21',
 '2015-01-22',
 '2015-01-23',
 '2015-01-24',
 '2015-01-25',
 '2015-01-26',
 '2015-01-27',
 '2015-01-28',
 '2015-01-29',
 '2015-01-30',
 '2015-01-31',
 '2015-02-01',
 '2015-02-02',
 '2015-02-03',
 '2015-02-04',
 '2015-02-05',
 '2015-02-06',
 '2015-02-07',
 '2015-02-08',
 '2015-02-09',
 '2015-02-10',
 '2015-02-11',
 '2015-02-12',
 '2015-02-13',
 '2015-02-14',
 '2015-02-15',
 '2015-02-16',
 '2015-02-17',
 '2015-02-18',
 '2015-02-19',
 '2015-02-20',
 '2015-02-21',
 '2015-02-22',
 '2015-02-23',
 '2015-02-24',
 '2015-02-25',
 '2015-02-26',
 '2015-02-27',
 '2015-02-28',
 '2015-03-01',
 '2015-03-02',
 '2015-03-03',
 '2015-03-04',
 '2015-03-05',
 '2015-03-06',
 '2015-03-07',
 '2015-03-09',
 '2015-03-10',
 '2015-03-11',
 '2015-03-12',
 '2015-03-13',
 '2015-03-14',
 '2015-03-15',
 '2015-03-16',
 '2015-03-17',
 '2015-03-18',
 '2015-03-19',
 '2015-03-20',
 '2015-03-21',
 '2015-03-22',
 '2015-03-23',
 '2015-03-24',
 '2015-03-25',
 '2015-03-26',
 '2015-03-27',
 '2015-03-28',
 '2015-03-29',
 '2015-03-30',
 '2015-03-31',
 '2015-04-01',
 '2015-04-02',
 '2015-04-03',
 '2015-04-04',
 '2015-04-05',
 '2015-04-06',
 '2015-04-07',
 '2015-04-08',
 '2015-04-09',
 '2015-04-10',
 '2015-04-11',
 '2015-04-12',
 '2015-04-13',
 '2015-04-14',
 '2015-04-15',
 '2015-04-16',
 '2015-04-17',
 '2015-04-18',
 '2015-04-19',
 '2015-04-20',
 '2015-04-21',
 '2015-04-22',
 '2015-04-23',
 '2015-04-24',
 '2015-04-25',
 '2015-04-26',
 '2015-04-27',
 '2015-04-28',
 '2015-04-29',
 '2015-04-30',
 '2015-05-01',
 '2015-05-02',
 '2015-05-03',
 '2015-05-04',
 '2015-05-05',
 '2015-05-06',
 '2015-05-07',
 '2015-05-08',
 '2015-05-09',
 '2015-05-10',
 '2015-05-11',
 '2015-05-12',
 '2015-05-13',
 '2015-05-14',
 '2015-05-15',
 '2015-05-16',
 '2015-05-17',
 '2015-05-18',
 '2015-05-19',
 '2015-05-20',
 '2015-05-21',
 '2015-05-22',
 '2015-05-23',
 '2015-05-24',
 '2015-05-25',
 '2015-05-26',
 '2015-05-27',
 '2015-05-28',
 '2015-05-29',
 '2015-05-30',
 '2015-05-31',
 '2015-06-01',
 '2015-06-02',
 '2015-06-03',
 '2015-06-04',
 '2015-06-06',
 '2015-06-07',
 '2015-06-08',
 '2015-06-09',
 '2015-06-10',
 '2015-06-11',
 '2015-06-12',
 '2015-06-13',
 '2015-06-14',
 '2015-06-15',
 '2015-06-16',
 '2015-06-17',
 '2015-06-18',
 '2015-06-19',
 '2015-06-20',
 '2015-06-21',
 '2015-06-22',
 '2015-06-24',
 '2015-06-25',
 '2015-06-26',
 '2015-06-27',
 '2015-06-28',
 '2015-06-29',
 '2015-06-30',
 '2015-07-01',
 '2015-07-02',
 '2015-07-03',
 '2015-07-04',
 '2015-07-05',
 '2015-07-06',
 '2015-07-07',
 '2015-07-09',
 '2015-07-10',
 '2015-07-11',
 '2015-07-12',
 '2015-07-13',
 '2015-07-14',
 '2015-07-15',
 '2015-07-16',
 '2015-07-17',
 '2015-07-18',
 '2015-07-19',
 '2015-07-20',
 '2015-07-21',
 '2015-07-22',
 '2015-07-23',
 '2015-07-24',
 '2015-07-25',
 '2015-07-26',
 '2015-07-27',
 '2015-07-28',
 '2015-07-29',
 '2015-07-30',
 '2015-07-31',
 '2015-08-01',
 '2015-08-02',
 '2015-08-03',
 '2015-08-04',
 '2015-08-05',
 '2015-08-06',
 '2015-08-07',
 '2015-08-08',
 '2015-08-09',
 '2015-08-10',
 '2015-08-11',
 '2015-08-12',
 '2015-08-13',
 '2015-08-14',
 '2015-08-16',
 '2015-08-17',
 '2015-08-18',
 '2015-08-19',
 '2015-08-20',
 '2015-08-21',
 '2015-08-22',
 '2015-08-23',
 '2015-08-24',
 '2015-08-25',
 '2015-08-26',
 '2015-08-27',
 '2015-08-28',
 '2015-08-29',
 '2015-08-30',
 '2015-08-31',
 '2015-09-01',
 '2015-09-02',
 '2015-09-03',
 '2015-09-04',
 '2015-09-05',
 '2015-09-06',
 '2015-09-07',
 '2015-09-08',
 '2015-09-09',
 '2015-09-10',
 '2015-09-11',
 '2015-09-12',
 '2015-09-13',
 '2015-09-14',
 '2015-09-15',
 '2015-09-16',
 '2015-09-19',
 '2015-09-20',
 '2015-09-21',
 '2015-09-22',
 '2015-09-23',
 '2015-09-24',
 '2015-09-25',
 '2015-09-26',
 '2015-09-27',
 '2015-09-28',
 '2015-09-29',
 '2015-09-30',
 '2015-10-01',
 '2015-10-02',
 '2015-10-03',
 '2015-10-04',
 '2015-10-05',
 '2015-10-06',
 '2015-10-07',
 '2015-10-08',
 '2015-10-09',
 '2015-10-10',
 '2015-10-11',
 '2015-10-12',
 '2015-10-13',
 '2015-10-14',
 '2015-10-15',
 '2015-10-16',
 '2015-10-17',
 '2015-10-18',
 '2015-10-19',
 '2015-10-20',
 '2015-10-21',
 '2015-10-22',
 '2015-10-23',
 '2015-10-24',
 '2015-10-25',
 '2015-10-26',
 '2015-10-27',
 '2015-10-28',
 '2015-10-29',
 '2015-10-30',
 '2015-10-31',
 '2015-11-01',
 '2015-11-02',
 '2015-11-03',
 '2015-11-04',
 '2015-11-05',
 '2015-11-06',
 '2015-11-07',
 '2015-11-08',
 '2015-11-09',
 '2015-11-10',
 '2015-11-11',
 '2015-11-12',
 '2015-11-13',
 '2015-11-14',
 '2015-11-15',
 '2015-11-16',
 '2015-11-17',
 '2015-11-18',
 '2015-11-19',
 '2015-11-20',
 '2015-11-21',
 '2015-11-22',
 '2015-11-23',
 '2015-11-24',
 '2015-11-25',
 '2015-11-26',
 '2015-11-28',
 '2015-11-29',
 '2015-11-30',
 '2015-12-01',
 '2015-12-02',
 '2015-12-03',
 '2015-12-04',
 '2015-12-05',
 '2015-12-06',
 '2015-12-07',
 '2015-12-08',
 '2015-12-09',
 '2015-12-10',
 '2015-12-11',
 '2015-12-12',
 '2015-12-13',
 '2015-12-14',
 '2015-12-15',
 '2015-12-17',
 '2015-12-19',
 '2015-12-20',
 '2015-12-21',
 '2015-12-22',
 '2015-12-23',
 '2015-12-24',
 '2015-12-25',
 '2015-12-26',
 '2015-12-27',
 '2015-12-28',
 '2015-12-29',
 '2015-12-30']

In [7]:
stock_names = [stock.name for stock in list(tweet_dir.rglob("*")) if stock.is_dir()]
list.sort(stock_names)

stock_ids = [i for i in range(len(stock_names))]
stock_name_to_ids = dict(zip(stock_names, stock_ids))
stock_name_to_ids

num_stocks = len(stock_names)

In [66]:
tokens_file = dataset_dir / "all_tweets_tokenized.jsonl"
bad_data_file = dataset_dir / "bad_data.jsonl"

buffer = []
buffer_size = 100_000
lines = 0


with open(json_file, "r", encoding="utf-8") as f, open(tokens_file, "w", encoding="utf-8") as o, open(bad_data_file, "w", encoding="utf-8") as b:
    for line in f:

        entry = json.loads(line)

        stock_name = entry["stock"]
        tweet = entry["tweet"]
        date = entry["date"]

        if date not in all_dates:
            continue


        patterns = [
            rf"\${stock_name}(?=\s|$|\W)", # strict match
            rf"\${stock_name}" # loose match
        ]

        success = False
        for pattern in patterns:
            masked_tweet = re.sub(pattern, "<MASK>", tweet, flags=re.IGNORECASE)
            masked_tweet_tokenized = slot_spm.encode(masked_tweet)

            if mask_id in masked_tweet_tokenized:
                mask_idx = masked_tweet_tokenized.index(mask_id)
                success = True
                break

        if not success:
            bad_entry = {
                "stock": stock_name,
                "tweet": slot_spm.decode(masked_tweet_tokenized)
            }
            b.write(json.dumps(bad_entry) + "\n")
            continue

        # masked_tweet_tokenized = [
        #     tok if tok not in rare_tokens else unk_id
        #     for tok in masked_tweet_tokenized
        # ]


        tokenized_tweet = {
            "date": date,
            "tweet": masked_tweet_tokenized,
            "stock_id": stock_name_to_ids[stock_name],
            "mask_idx": mask_idx
        }


        buffer.append(json.dumps(tokenized_tweet))

        if len(buffer) >= buffer_size:
            o.write("\n".join(buffer) + "\n")
            lines += len(buffer)
            buffer.clear()

            print(f"{lines} lines written")

    if buffer:
        o.write("\n".join(buffer) + "\n")
        lines += len(buffer)
        print(f"{lines} lines written")

100000 lines written
106049 lines written

### Put all the data into lists

In [102]:
num_dates = len(all_dates)
tweet_tokens_by_date = [[] for i in range(num_dates)]
mask_indices_by_date = [[] for i in range(num_dates)]


tweet_tokens = []
mask_indices = []
y = []

with open(tokens_file, "r") as f:
    for line in f:
        entry = json.loads(line)

        date = all_dates.index(entry["date"])

        tokens = [int(tok) for tok in entry["tweet"]]
        idx = entry["mask_idx"]
        label = entry["stock_id"]

        tweet_tokens.append(tokens)
        mask_indices.append(idx)
        y.append(label)

        tweet_tokens_by_date[date].append(tokens)
        mask_indices_by_date[date].append(idx)

In [42]:
for i in range(5):
    print(all_dates[i] + ":", tweet_tokens_by_date[i])
    print(all_dates[i] + ":", mask_indices_by_date[i])
    print()

2014-01-02: [[7, 3, 35, 604, 1313, 11, 5504, 328, 82, 267, 26, 880, 1890, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [18, 7, 14, 12, 10, 13, 106, 28, 15, 209, 60, 282, 92, 770, 25, 480, 1524, 323, 2336, 2449, 86, 36, 8, 7, 3], [18, 7, 14, 12, 10, 13, 96, 144, 132, 157, 415, 27, 368, 40, 972, 3274, 1072, 1767, 1201, 22, 24, 285, 6, 279, 6, 254, 7, 3, 122, 8], [7, 14, 12, 10, 13, 7, 3, 1693, 46, 3159, 304, 46, 6609, 660, 5411, 176], [5876, 16, 3063, 91, 2432, 28, 15, 310, 44, 16, 7, 3, 76, 20, 723, 215, 5442, 40, 658, 3754, 142, 8], [7, 3, 2930, 40, 7, 1097, 120, 4715, 4538, 988, 15, 20, 1008, 2385, 8], [7, 3, 35, 401, 15, 6085, 336, 20, 89, 301, 1594, 1459, 292, 22, 368, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [18, 7, 14, 12, 10, 13, 96, 144, 132, 157, 415, 27, 368, 40, 972, 3274, 1072, 1767, 1201, 22, 24, 285, 6, 279, 6, 254, 7, 3, 122, 8], [18, 7, 14, 12, 10, 13, 96, 144, 132, 157, 415, 27, 368, 40, 972, 3274, 1072, 1767, 1201, 22, 24, 285, 6, 279, 6, 254, 7, 3, 122, 8], [202, 78, 186, 144, 331, 27, 263, 147, 368, 39, 106, 78, 7, 969, 16, 7, 3, 6, 2241, 6, 21, 6, 4191, 6, 1270], [18, 7, 14, 12, 10, 13, 96, 144, 132, 157, 415, 27, 368, 40, 972, 3274, 1072, 1767, 1201, 22, 24, 285, 6, 279, 6, 254, 7, 3, 122, 8], [7, 3, 239, 79, 37, 3852, 1313, 5504, 328, 82, 267, 26, 880, 1890, 8], [18, 7, 14, 12, 10, 13, 60, 249, 58, 5307, 22, 1614, 378, 7, 15, 113, 45, 36, 52, 28, 15, 2962, 243, 363, 28, 23, 307, 655, 27, 7, 3, 426, 11, 57, 2537, 225, 24, 269, 1199, 265, 15, 11, 8], [18, 7, 14, 12, 10, 13, 96, 144, 132, 157, 415, 27, 368, 40, 972, 3274, 1072, 1767, 1201, 22, 24, 285, 6, 279, 6, 254, 7, 3, 122, 8], [18, 7, 14, 12, 10, 13, 96, 144, 132, 157, 415, 27, 368, 40, 972, 3274, 1072, 1767, 1201, 22, 24, 285, 6, 279, 6, 254, 7, 3, 122, 8], [7, 3, 35, 60, 66, 92, 24, 3871, 7, 2349, 23, 963, 34, 288, 40, 121, 1112, 304, 697, 578, 1797, 52, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [82, 7, 3324, 16, 3573, 70, 7222, 4677, 15, 17, 4597, 1223, 616, 812, 70, 5969, 17, 65, 45, 36, 169, 1892, 15, 8, 6, 55, 6, 118, 6, 284, 7, 3, 6, 64, 6, 980], [68, 177, 25, 82, 869, 72, 267, 11, 453, 2796, 95, 537, 25, 7, 3, 869, 274, 394, 680, 265, 17, 1987, 2170, 28, 23, 151, 54, 20, 92, 466, 516, 11], [7, 3, 404, 603, 372, 60, 6213, 15, 1311, 71, 619, 1380, 17, 40, 89, 8], [7, 3, 4916, 46, 24, 474, 7, 3699, 54, 1440, 91, 1228, 8], [7, 3, 4539, 83, 4563, 1435, 165, 40, 1134, 811, 15, 15, 3986, 967, 290, 70, 5626, 8], [7, 3, 938, 28, 15, 225, 938, 24, 330, 73, 3413, 137, 7868, 3432, 28, 15, 368, 144, 491, 361, 261, 71, 25, 6, 5780, 169, 337, 11], [66, 368, 92, 60, 28, 15, 104, 1489, 34, 3530, 130, 48, 1284, 129, 267, 34, 5096, 37, 175, 1623, 238, 3327, 48, 1284, 7, 3], [7, 3, 35, 579, 37, 747, 16, 60, 2262, 26, 2832, 4713, 36, 79, 20, 538, 368, 59, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [219, 3761, 666, 28, 15, 79, 35, 7, 3, 297, 221, 369, 1584, 41, 841, 8], [18, 7, 14, 12, 10, 13, 96, 144, 132, 157, 415, 27, 368, 40, 972, 3274, 1072, 1767, 1201, 22, 24, 285, 6, 279, 6, 254, 7, 3, 122, 8], [7, 3, 24, 2173, 256, 1494, 2466, 16, 60, 17, 2471, 17, 8, 288, 40, 2148, 5728, 15, 8], [18, 7, 14, 12, 10, 13, 60, 6247, 17, 3690, 131, 85, 105, 996, 795, 15, 76, 26, 256, 332, 8, 7, 3], [18, 7, 14, 12, 10, 13, 96, 144, 132, 157, 415, 27, 368, 40, 972, 3274, 1072, 1767, 1201, 22, 24, 285, 6, 279, 6, 254, 7, 3, 122, 8], [18, 7, 14, 12, 10, 13, 96, 144, 132, 157, 415, 27, 368, 40, 972, 3274, 1072, 1767, 1201, 22, 24, 285, 6, 279, 6, 254, 7, 3, 122, 8], [7, 3, 209, 41, 870, 1140, 1780, 1505, 137, 93, 24, 3248, 1300, 1911, 2051, 997, 39, 8], [72, 489, 7, 3, 7, 7381, 864, 78, 1201, 76, 25, 1260, 114, 11], [560, 3510, 2269, 90, 26, 6, 4772, 17, 6, 1325, 23, 17, 7, 3, 17, 6, 115, 40, 6, 74, 8], [7, 3, 144, 256, 1921, 40, 2503, 16, 60, 17, 464, 17, 4097, 17, 25, 1857, 38, 697, 3108, 91, 59, 8], [18, 7, 14, 12, 10, 13, 3727, 393, 93, 7, 3, 40, 116, 1765, 71, 1521, 212, 342, 228, 5952, 48, 6543, 37, 15, 38, 493, 4061, 238, 53, 22, 517, 1457, 142, 3650, 816, 719, 17, 5440, 114, 22, 7, 14, 12, 10, 13, 8], [18, 7, 14, 12, 10, 13, 4655, 111, 3941, 2647, 2960, 20, 724, 50, 20, 7, 2316, 1243, 37, 7219, 186, 6109, 44, 8, 7, 3, 9, 1923, 6154, 15, 9, 2542, 15, 48, 2018, 33], [7, 3, 41, 841, 26, 156, 7, 1849, 460, 15, 11, 272, 593, 27, 141, 4603], [7, 3, 285, 34, 421, 173, 48, 67, 741, 154, 219, 848, 20, 828, 22, 368, 8], [7, 3, 35, 2987, 144, 383, 4304, 27, 2922, 267, 26, 4200, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 1550, 2598, 2965, 33, 11, 793, 27, 2913, 5356, 7511, 366, 20, 162, 25, 4573, 7, 2365, 40, 713, 105, 93, 1543, 30, 46, 3044], [18, 7, 14, 12, 10, 13, 7, 3, 8], [387, 1222, 16, 6087, 37, 7235, 37, 7869, 16, 7, 3, 122, 37, 10, 113, 86, 615, 86, 615, 86, 615, 86, 36, 8], [6, 38, 1921, 7, 3, 20, 6, 908, 93, 2965, 11, 11, 7, 84, 193, 70, 23, 1502, 20, 6, 2850, 93, 6, 2270, 8], [7, 3, 35, 355, 5112, 494, 141, 787, 25, 252, 1022, 22, 1614, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [4067, 11, 7, 14, 12, 10, 13, 184, 2170, 28, 23, 68, 224, 61, 317, 194, 34, 7, 3, 459, 50, 177, 191, 39], [7, 3, 35, 66, 4956, 180, 15, 248, 2768, 5103, 6108, 46, 7, 2317, 1659, 521, 328, 39, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [18, 7, 14, 12, 10, 13, 185, 2156, 959, 6888, 79, 27, 1614, 16, 267, 37, 1300, 2668, 76, 8, 7, 3, 6, 153, 6, 3481, 6, 526, 6, 5000, 6, 75, 6, 86, 111, 15, 6, 33], [18, 7, 14, 12, 10, 13, 1715, 3401, 193, 3, 227, 381, 25, 291, 1257, 1056, 319, 1200, 713, 186, 558, 11, 286, 3083, 20, 24, 5025, 44], [7, 3, 1921, 6, 67, 20, 6, 908, 93, 2965, 11, 11, 7, 84, 193, 70, 23, 1502, 20, 6, 2850, 93, 6, 2270, 8], [18, 7, 14, 12, 10, 13, 185, 2156, 959, 6888, 79, 27, 1614, 16, 267, 37, 1300, 2668, 76, 8, 6, 311, 7, 3, 6, 3481, 6, 526, 6, 5000, 6, 75, 6, 86, 111, 15, 6, 33], [7, 3, 35, 2765, 20, 2068, 1730, 2119, 1974, 15, 17, 3139, 30, 195, 37, 7639, 1595, 40, 727, 15, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 25, 3226, 160, 6400, 16, 24, 320, 797, 252, 523, 117, 8], [18, 7, 14, 12, 10, 13, 1288, 1158, 1408, 422, 355, 1445, 255, 683, 1345, 1169, 1438, 346, 1286, 375, 1151, 1339, 1397, 1079, 1429, 1390, 9, 1806, 116, 3, 1977], [7, 3, 404, 4558, 372, 90, 3282, 23, 16, 604, 573, 381, 1039, 880, 8], [7, 3, 7, 1996, 1196, 565, 3922, 1331, 478, 46, 20, 92, 89, 150, 292, 8], [573, 9, 471, 5464, 15, 16, 6, 4625, 6, 94, 6, 7440, 6, 30, 222, 6, 111, 655, 6, 6640, 6, 176, 15, 6, 83, 73, 6, 4289, 6, 4820, 6, 377, 85, 6, 3932, 6, 3352, 7, 3], [202, 78, 186, 144, 331, 27, 263, 147, 368, 39, 106, 78, 7, 969, 16, 6, 19, 6, 2241, 7, 3, 6, 4191, 6, 1270], [7992, 15, 1537, 1933, 345, 93, 110, 143, 7902, 15, 2302, 191, 3226, 4448, 15, 409, 409, 24, 7, 7488, 1645, 8, 7, 3, 6, 55], [7, 21, 4663, 11, 2064, 7, 3, 9, 661, 8], [645, 689, 215, 48, 75, 741, 887, 41, 25, 327, 49, 20, 61, 16, 645, 689, 59, 7, 3, 8], [6, 1409, 2045, 251, 106, 20, 335, 105, 274, 6, 1409, 41, 25, 61, 350, 129, 214, 11, 728, 305, 79, 11, 7, 3, 6, 1896, 6, 4395, 6, 660, 8], [18, 7, 14, 12, 10, 13, 185, 2156, 959, 6888, 79, 27, 1614, 16, 267, 37, 1300, 2668, 76, 8, 6, 311, 6, 153, 6, 3481, 6, 526, 6, 5000, 7, 3, 6, 86, 111, 15, 6, 33], [7, 3, 121, 47, 7, 16, 1080, 3919, 27, 2748, 82, 57, 2186, 3390, 176, 20, 25, 5552, 30, 2721, 812, 8], [157, 2010, 6517, 93, 24, 486, 2608, 787, 25, 4708, 3590, 575, 594, 22, 1614, 11, 351, 321, 78, 7, 3, 6, 175, 6, 271, 6, 891, 8], [7, 3, 35, 60, 210, 4924, 7, 3904, 89, 487, 100, 2434, 616, 2945, 121, 22, 72, 558, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 2134, 1816, 233, 81, 17, 121, 3335, 76, 269, 500, 34, 4278, 1875, 27, 6136, 397, 696, 8], [18, 7, 14, 12, 10, 13, 621, 113, 45, 36, 280, 1940, 3083, 71, 241, 1038, 20, 281, 247, 94, 842, 22, 1008, 34, 24, 1175, 5076, 3000, 4157, 3853, 16, 8, 7, 3, 100, 7, 14, 12, 10, 13], [320, 303, 5971, 16, 530, 65, 45, 36, 530, 7, 3, 8], [858, 317, 219, 2478, 323, 24, 392, 26, 6, 1956, 6, 62, 6, 715, 7, 3], [7, 3, 35, 4445, 144, 200, 7553, 49, 331, 27, 368, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [157, 2010, 6517, 93, 24, 486, 2608, 787, 25, 4708, 3590, 575, 594, 22, 1614, 11, 351, 321, 78, 6, 29, 7, 3, 6, 271, 6, 891, 8], [244, 2105, 111, 4151, 170, 2067, 7, 3, 255, 8, 9, 7061, 9, 273, 9, 1216, 6248, 682, 9, 6266, 135], [288, 547, 7, 16, 288, 7939, 30, 1080, 7, 3, 8], [7, 1604, 367, 54, 3989, 1864, 6560, 28, 22, 24, 992, 2733, 16, 24, 1211, 34, 288, 8, 7, 3, 9, 917, 9, 3889], [7, 3, 35, 404, 603, 372, 27, 30, 15, 1292, 111, 2469, 107, 92, 5109, 5497, 1849, 20, 1589, 288, 16, 4747, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 1432, 20, 3514, 71, 6088, 15, 243, 639, 15, 286, 1858, 1558, 534, 3444, 15, 20, 1589, 39, 26, 687, 3586, 289, 17, 225, 9, 423, 238, 884, 2039, 28, 15, 2760, 1716, 493, 37, 1387, 3694, 37, 1973, 175, 109, 3586, 289, 39, 9, 2266], [588, 46, 5135, 11, 4416, 1013, 486, 40, 1494, 2986, 58, 11, 4922, 4910, 3942, 2995, 125, 3750, 290, 722, 296, 846, 2420, 1167, 17, 5972, 15, 20, 2639, 3103, 7, 3, 7, 6132], [7, 3, 404, 603, 372, 2802, 578, 419, 15, 646, 2743, 34, 1799, 655, 15, 3614, 17, 40, 89, 8], [9, 262, 197, 1253, 27, 6, 2898, 17, 6, 259, 17, 7, 3, 17, 6, 2481, 17, 65, 45, 36, 6, 1268, 93, 22, 8491, 114, 16, 8, 9, 262, 9, 6562, 6345], [49, 2217, 27, 72, 951, 8, 6, 1617, 6, 778, 6, 3041, 6, 8073, 6, 3037, 6, 4657, 6, 83, 432, 15, 6, 3034, 6, 55, 7, 3, 130], [157, 16, 2115, 7, 3, 7, 15, 16, 2115, 1795, 8], [7, 3, 35, 7, 3687, 408, 719, 336, 307, 4083, 2183, 1501, 1111, 6034, 22, 2180, 37, 289, 1519, 1004, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 659, 47, 11, 7, 16, 260, 518, 57, 659, 1156, 82, 393, 26, 3662, 2343, 1268, 423, 8], [7, 14, 12, 10, 13, 225, 143, 6879, 143, 7, 3, 48, 5418, 6, 670, 41, 593, 89, 4368, 30, 20, 1030, 439, 566, 38, 1188, 53], [7, 3, 35, 1614, 6453, 96, 5453, 15, 5005, 6292, 15, 979, 402, 20, 1667, 34, 170, 1098, 719, 93, 821, 590, 1212, 83, 33, 155, 86, 36, 8, 9, 63, 9, 42, 9, 253], [7, 3, 4916, 4654, 707, 41, 25, 2754, 3398, 15, 1167, 65, 45, 36, 305, 132, 494, 622, 69, 8], [18, 7, 14, 12, 10, 13, 2031, 1030, 1537, 145, 666, 503, 1098, 1636, 361, 83, 142, 1221, 296, 424, 1558, 2398, 4446, 1283, 3, 8], [6986, 1746, 81, 10, 62, 31, 10, 31, 111, 130, 44, 7, 227, 130, 147, 3, 1135, 3, 4155, 44, 6986, 130, 1746, 81, 10, 163, 1527, 70, 316, 130, 44, 6986, 2866, 31, 10, 147, 1105, 130, 44, 6986, 1294, 15, 5238, 10, 147, 1105, 130, 44, 6986, 43, 468, 4653, 946, 37, 294, 130, 44, 6986, 1895, 30, 100, 612, 179, 130, 44, 6986, 31, 1102, 145, 131, 228, 130, 44, 6986, 3749, 31, 31, 4618, 130, 44], [9, 23, 1069, 46, 10, 23, 1069, 46, 9, 3297, 7, 8321, 3, 4043, 1149, 26, 9, 1250, 439, 113, 86, 615, 86, 36, 7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 7, 14, 12, 10, 13, 9, 228, 1076, 471], [18, 7, 14, 12, 10, 13, 2031, 1030, 1537, 145, 666, 503, 1098, 1636, 361, 83, 142, 1221, 296, 424, 1558, 2398, 4446, 1283, 3, 8], [18, 7, 14, 12, 10, 13, 2031, 1030, 1537, 145, 666, 503, 1098, 1636, 361, 83, 142, 1221, 296, 424, 1558, 2398, 4446, 1283, 3, 8], [41, 2381, 637, 41, 218, 26, 7, 3, 57, 9, 5095, 11, 96, 512, 7, 6962, 5646, 337, 169, 6, 1386, 11, 1810, 11, 89, 391, 26, 8, 9, 42], [7, 3, 27, 30, 4766, 15, 2148, 6151, 831, 27, 5366, 688, 8], [7, 3, 49, 28, 15, 325, 444, 343, 35, 2188, 319, 47, 11, 520, 273, 16, 268, 634, 7, 2734, 1062, 719, 47, 59, 8], [858, 317, 219, 2478, 323, 24, 392, 26, 6, 1956, 7, 3, 6, 715, 6, 84], [303, 643, 193, 6831, 2846, 2088, 834, 16, 1005, 986, 378, 11, 6881, 8, 7, 3, 6, 457], [7, 3, 368, 1512, 630, 22, 24, 1361, 354, 554, 8], [18, 7, 14, 12, 10, 13, 602, 37, 540, 401, 4773, 15, 104, 73, 1020, 1558, 1480, 363, 1655, 213, 578, 17, 130, 887, 264, 3953, 556, 238, 2730, 71, 59, 7, 2234, 213, 578, 16, 8, 7, 3], [560, 3510, 2269, 90, 26, 6, 4772, 17, 6, 1325, 23, 17, 6, 19, 17, 7, 3, 40, 6, 74, 8], [327, 37, 5316, 46, 2708, 4974, 643, 141, 210, 1722, 100, 25, 219, 2832, 8, 6, 2874, 6, 2075, 15, 6, 4484, 6, 1653, 6, 2636, 6, 675, 7, 3]]
2014-01-02: [1, 24, 27, 6, 11, 1, 1, 27, 27, 16, 27, 1, 30, 27, 27, 1, 31, 14, 1, 1, 1, 1, 25, 1, 8, 27, 1, 22, 27, 27, 1, 3, 13, 1, 10, 25, 1, 1, 1, 1, 7, 10, 4, 1, 18, 1, 21, 9, 1, 23, 1, 1, 29, 1, 1, 38, 20, 23, 6, 18, 23, 31, 1, 20, 1, 1, 33, 10, 15, 1, 22, 7, 9, 19, 1, 1, 31, 1, 12, 27, 4, 1, 1, 10, 1, 1, 24, 15, 12, 24, 24, 7, 1, 1, 11, 15, 1, 38, 16, 29]


### Pad the token data and shuffle

In [103]:
max_len = max(len(tweet) for tweet in tweet_tokens)


X = [tweet + [pad_id] * (max_len - len(tweet))
    for tweet in tweet_tokens]


X = torch.tensor(X, dtype=torch.long)
y = torch.tensor(y, dtype=torch.long)
mask_indices = torch.tensor(mask_indices, dtype=torch.long)

perm = torch.randperm(X.size(0))
X, y, mask_indices = X[perm], y[perm], mask_indices[perm]

X, X.shape, y, y.shape, mask_indices, mask_indices.shape

(tensor([[  18,    7,   14,  ...,    4,    4,    4],
         [  18,    7,   14,  ...,    4,    4,    4],
         [8352,  783,    7,  ...,    4,    4,    4],
         ...,
         [  18,    7,   14,  ...,    4,    4,    4],
         [3543,   17,   47,  ...,    4,    4,    4],
         [  18,    7,   14,  ...,    4,    4,    4]]),
 torch.Size([106049, 147]),
 tensor([31, 31, 85,  ..., 39, 34, 26]),
 torch.Size([106049]),
 tensor([17,  7, 25,  ..., 28, 19, 35]),
 torch.Size([106049]))

In [104]:
# (num_dates, num_tweets_for_that_date, seq_len)
X_by_date = [
    torch.tensor(
        [tweet + [pad_id] * (max_len - len(tweet)) for tweet in tweet_tokens_by_date[d]],
        dtype=torch.long
    )
    for d in range(num_dates)
]

mask_indices_by_date = [
    torch.tensor(mask_indices_by_date[d], dtype=torch.long)
    for d in range(num_dates)
]

X_by_date[0], X_by_date[0].shape, mask_indices_by_date[0], mask_indices_by_date[0].shape

(tensor([[   7,    3,   35,  ...,    4,    4,    4],
         [  18,    7,   14,  ...,    4,    4,    4],
         [  18,    7,   14,  ...,    4,    4,    4],
         ...,
         [  18,    7,   14,  ...,    4,    4,    4],
         [ 560, 3510, 2269,  ...,    4,    4,    4],
         [ 327,   37, 5316,  ...,    4,    4,    4]]),
 torch.Size([100, 147]),
 tensor([ 1, 24, 27,  6, 11,  1,  1, 27, 27, 16, 27,  1, 30, 27, 27,  1, 31, 14,
          1,  1,  1,  1, 25,  1,  8, 27,  1, 22, 27, 27,  1,  3, 13,  1, 10, 25,
          1,  1,  1,  1,  7, 10,  4,  1, 18,  1, 21,  9,  1, 23,  1,  1, 29,  1,
          1, 38, 20, 23,  6, 18, 23, 31,  1, 20,  1,  1, 33, 10, 15,  1, 22,  7,
          9, 19,  1,  1, 31,  1, 12, 27,  4,  1,  1, 10,  1,  1, 24, 15, 12, 24,
         24,  7,  1,  1, 11, 15,  1, 38, 16, 29]),
 torch.Size([100]))

### Train/val/test split

In [105]:
data_len = len(y)

train_end = int(data_len * 0.90)
val_end = int(data_len * 1.00)

X_train, y_train, mask_train = X[ : train_end], y[ : train_end], mask_indices[ : train_end]
X_val, y_val, mask_val = X[train_end : val_end], y[train_end : val_end], mask_indices[train_end : val_end]
# X_test, y_test, mask_test = X[val_end : ], y[val_end : ], mask_indices[val_end : ]

print(f"X_train shape: {X_train.shape}. y_train shape: {y_train.shape}")
print(f"X_val shape: {X_val.shape}. y_val shape: {y_val.shape}")
# print(f"X_test shape: {X_test.shape}. y_test shape: {y_test.shape}")

mask_train.shape, mask_val.shape #, mask_test.shape

X_train shape: torch.Size([95444, 147]). y_train shape: torch.Size([95444])
X_val shape: torch.Size([10605, 147]). y_val shape: torch.Size([10605])

(torch.Size([95444]), torch.Size([10605]))

### Datasets

In [106]:
class SLOTTokensDataset(Dataset):
    def __init__(self, x, y, mask_idx):
        self.x = x
        self.y = y
        self.mask_idx = mask_idx

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx], self.mask_idx[idx]

In [107]:
train_dataset = SLOTTokensDataset(X_train, y_train, mask_train)
val_dataset = SLOTTokensDataset(X_val, y_val, mask_val)
# test_dataset = SLOTTokensDataset(X_test, y_test, mask_test)

train_dataset[0]

(tensor([  18,    7,   14,   12,   10,   13, 3994,  447,   26, 2193,   48,   73,
          525,  741,    6,   55,    7,    3,    6, 3874,    6,  515,    6,  235,
            8,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
            4,    4,    4]),
 tensor(31),
 tensor(17))

### Model Definition

In [110]:

class StockIdentification(nn.Module):
    def __init__(self, num_stocks, embd_size, hidden_size, vocab_size):
        super().__init__()
        self.H = hidden_size


        self.stock_embd = nn.Embedding(num_embeddings=num_stocks, embedding_dim=2*hidden_size)


        self.token_embd = nn.Embedding(num_embeddings=vocab_size,
                                       embedding_dim=embd_size,
                                       padding_idx=pad_id)


        self.bi_lstm = nn.LSTM(
            input_size=embd_size,
            hidden_size=hidden_size,
            bidirectional=True,
            batch_first=True,
        )

        self.dropout = nn.Dropout(0.1)

        self.init_weights()

    def init_weights(self):
        nn.init.normal_(self.token_embd.weight, mean=0.0, std=0.01)
        nn.init.normal_(self.stock_embd.weight, mean=0.0, std=0.01)

        for name, param in self.bi_lstm.named_parameters():
            if "bias" in name:
                nn.init.zeros_(param)
                # set forget gate bias to 1
                # [i, f, g, o]
                param.data[self.H : 2*self.H].fill_(1.0)
            elif "weight_ih" in name:
                nn.init.kaiming_normal_(param)
            elif "weight_hh" in name:
                nn.init.orthogonal_(param)


    def forward(self, x, mask_indices):
        # x: (B, T)
        # mask_indices: (B,). The index of the <MASK> token for each tweet
        batch_size = x.size(0)
        token_embs = self.token_embd(x) # (B, T, embd_size)
        token_embs = self.dropout(token_embs)

        seq_lengths = (x != pad_id).sum(dim=-1).to("cpu")
        packed_token_embs = pack_padded_sequence(token_embs, seq_lengths, batch_first=True, enforce_sorted=False)

        # output: (B, T, 2*hidden_size)
        # h_n, c_n : (2*num_layers, B, hidden_size)
        output, (h_n, c_n) = self.bi_lstm(packed_token_embs)

        output, _ = pad_packed_sequence(output, batch_first=True)

        output = self.dropout(output)

        h_e = output[torch.arange(batch_size), mask_indices] # (B, 2*hidden_size)

        h_s = self.stock_embd.weight # (num_stocks, 2*hidden_size)
        h_e = F.normalize(h_e, dim=-1)
        h_s = F.normalize(h_s, dim=-1)
        logits = torch.matmul(h_e, h_s.T) #  (B, 2*hidden_size) @ (2*hidden_size, num_stocks) -> (B, num_stocks)


        return logits / 0.3, h_e, h_s

### Evaluation Functions

In [14]:
tweet_files_list = list(tweet_dir.rglob("*/*"))
list.sort(tweet_files_list)

tweet_files_stocks = [tweet.parent.name for tweet in tweet_files_list]
stock_counts = Counter(tweet_files_stocks)

stock_counts = torch.tensor([value for value in stock_counts.values()], dtype=torch.long)
stock_counts = stock_counts.to(device)

N = stock_counts.sum()
inv_freq = N / stock_counts
weights = torch.log1p(inv_freq)
weights = weights / weights.mean()
weights

tensor([0.7389, 1.1751, 0.8591, 1.0505, 1.6898, 0.8491, 0.7453, 0.8261, 0.8199,
        0.7714, 1.1916, 1.5983, 0.9514, 0.8787, 1.5644, 1.4985, 1.0618, 0.7638,
        0.8325, 0.8124, 1.0836, 1.0068, 0.8787, 1.3758, 0.7979, 0.8165, 0.7540,
        1.0836, 0.7962, 1.0179, 1.0078, 0.7399, 0.9836, 0.7882, 0.7432, 0.8452,
        1.0039, 1.3697, 1.1417, 1.1992, 0.7800, 0.8052, 0.7840, 0.8095, 0.9309,
        0.8662, 0.8055, 0.9605, 0.8977, 0.8954, 0.8371, 0.7546, 1.0296, 1.3420,
        0.9793, 0.8752, 1.0618, 0.7815, 0.9069, 0.8172, 0.8577, 1.4402, 0.9898,
        1.0697, 1.2761, 1.8615, 1.1966, 0.9198, 1.3884, 1.0158, 0.9810, 1.6389,
        1.1436, 0.7422, 1.0554, 1.0822, 1.1065, 1.2124, 1.1684, 0.8866, 0.9567,
        0.9256, 0.8063, 0.8199, 0.8289, 0.8055, 0.7918])

In [15]:
def evaluate(logits, stock_labels):
    # stock_labels: (B,)
    loss = F.cross_entropy(logits, stock_labels, weight=weights)

    stock_pred = torch.argmax(logits, dim=-1) # (B,)
    acc = (stock_pred == stock_labels).float().mean()

    return loss, acc

In [16]:
stock_id_to_name = {v: k for k, v in stock_name_to_ids.items()}

stock_queries = ["AAPL", "FB", "BA", "BAC"]
stock_query_ids = [stock_name_to_ids[name] for name in stock_queries]

In [18]:
def stock_cosine_similarities(model):

    h_s = model.stock_embd.weight # (num_stocks, embd_size)

    h_s_normalized = h_s / h_s.norm(dim=1, keepdim=True)
    h_s_sim = h_s_normalized @ h_s_normalized.T # (num_stocks, embd_size) @ (embd_size, num_stocks) -> (num_stocks, num_stocks)

    n = h_s_sim.size(0)
    h_s_sim.fill_diagonal_(float("-inf")) # h_s_sim[i][i] = -inf

    h_s_sim = h_s_sim[stock_query_ids] # (4, num_stocks)
    _, top3_indices = torch.topk(h_s_sim, k=3, dim=-1) # (4, 3)


    for query_idx, query in enumerate(stock_queries):
        print(f"\n{query}: ", end="")
        for neigh_idx in top3_indices[query_idx]:
            print(stock_id_to_name[int(neigh_idx.item())], end=", ")


def tweet_embedding_quality(model):

    tweet1 = "<MASK> iphone 6s spec leaks look good. excited. might even buy one." # $AAPL
    tweet2 = "rt AT_USER <MASK> $pep $dps $mnst traditional soft drinks in decline." # $KO

    eval_X = [slot_spm.encode(tweet1), slot_spm.encode(tweet2)]

    max_len = max(len(tweet) for tweet in eval_X)

    eval_X = [tweet + [pad_id] * (max_len - len(tweet)) for tweet in eval_X]

    eval_mask_indices = torch.tensor([eval_X[0].index(mask_id), eval_X[1].index(mask_id)])
    eval_X = torch.tensor(eval_X, dtype=torch.long)

    eval_X, eval_mask_indices = eval_X.to(device), eval_mask_indices.to(device)
    eval_logits, _, _ = model(eval_X, eval_mask_indices)

    eval_preds = F.softmax(eval_logits, dim=-1)
    _, eval_top3_indices = torch.topk(eval_preds, k=3, dim=-1)

    for i, stock in enumerate(eval_top3_indices):
        print()
        for pred in stock:
            print(f"{stock_id_to_name[pred.item()]}: {eval_preds[i][pred.item()].item():.2%}", end = " | ")

### Training Loop

In [80]:
lr = 1e-4
num_epochs = 50
batch_size = 256
num_stocks = len(stock_names)


model = StockIdentification(
    num_stocks=num_stocks,
    embd_size=128,
    hidden_size=64,
    vocab_size=vocab_size
)

model = model.to(device)

optimizer = torch.optim.AdamW(params = model.parameters(), lr=lr, weight_decay=1e-3)
scheduler = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(optimizer, T_0=10, T_mult=2, eta_min=1e-6)
# scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer=optimizer, T_max=num_epochs, eta_min=1e-6)

train_dataloader = DataLoader(train_dataset, batch_size, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size, shuffle=False)
# test_dataloader = DataLoader(test_dataset, batch_size, shuffle=False)

for epoch in range(num_epochs):
    train_loss = 0.0
    train_acc = 0.0


    model.train()
    for i, (X, y, mask_indices) in enumerate(train_dataloader):
        X, y, mask_indices = X.to(device), y.to(device).to(torch.long), mask_indices.to(device)


        logits, _, _ = model(X, mask_indices) # (B, num_stocks)

        loss, acc = evaluate(logits, y)

        train_loss += loss.detach().item()
        train_acc += acc.item()


        optimizer.zero_grad()

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        optimizer.step()

        # if i % 300 == 0:
            # print(f"Step: {i:04d} | Train loss: {loss:.4f} | Train acc: {100*acc:.2f}%")



    train_loss /= len(train_dataloader)
    train_acc /= len(train_dataloader)

    val_loss = 0.0
    val_acc = 0.0


    model.eval()
    with torch.inference_mode():
        for j, (X_val, y_val, mask_indices_val) in enumerate(val_dataloader):


            X_val, y_val, mask_indices_val = X_val.to(device), y_val.to(device), mask_indices_val.to(device)

            logits_val, _, _ = model(X_val, mask_indices_val)
            loss, acc = evaluate(logits_val, y_val)

            val_loss += loss.detach().item()
            val_acc += acc.item()

        val_loss /= len(val_dataloader)
        val_acc /= len(val_dataloader)


    stock_cosine_similarities(model)
    tweet_embedding_quality(model)


    scheduler.step()

    print(f"\nEpoch: {epoch} | Train loss: {train_loss:.4f} | Train acc: {100*train_acc:.2f}% | Val loss: {val_loss:.4f} | Val acc: {100*val_acc:.2f}%")
    print(f"Learning rate: {optimizer.param_groups[0]['lr']:6f}")

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, SO, PTR,
BAC: JPM, DIS, WFC,
AAPL: 19.82% | AMZN: 11.04% | FB: 9.73% |
KO: 5.56% | AAPL: 3.14% | BABA: 3.07% |
Epoch: 0 | Train loss: 3.3433 | Train acc: 27.79% | Val loss: 2.9928 | Val acc: 36.71%
Learning rate: 0.000098

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, NVS, PFE,
BAC: WFC, JPM, DIS,
AAPL: 25.12% | AMZN: 11.87% | FB: 10.17% |
KO: 5.50% | PEP: 3.03% | CELG: 2.35% |
Epoch: 1 | Train loss: 2.9183 | Train acc: 41.12% | Val loss: 2.8214 | Val acc: 43.22%
Learning rate: 0.000091

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, NVS, SNY,
BAC: WFC, JPM, C,
AAPL: 25.43% | AMZN: 11.49% | FB: 10.23% |
KO: 6.10% | PEP: 3.48% | GE: 2.44% |
Epoch: 2 | Train loss: 2.7800 | Train acc: 46.31% | Val loss: 2.7648 | Val acc: 45.79%
Learning rate: 0.000080

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, NVS, SNY,
BAC: WFC, JPM, C,
AAPL: 25.53% | AMZN: 13.16% | FB: 10.77% |
KO: 5.54% | PEP: 3.66% | AAPL: 2.57% |
Epoch: 3 | Train loss: 2.7112 | Train acc: 48.74% | Val loss: 2.7405 | Val acc: 46.11%
Learning rate: 0.000066

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, NVS, SNY,
BAC: WFC, JPM, C,
AAPL: 25.16% | AMZN: 13.32% | FB: 10.17% |
KO: 5.68% | PEP: 4.13% | GE: 2.55% |
Epoch: 4 | Train loss: 2.6655 | Train acc: 50.31% | Val loss: 2.7226 | Val acc: 47.46%
Learning rate: 0.000051

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, NVS, SNY,
BAC: WFC, JPM, C,
AAPL: 24.12% | AMZN: 14.04% | FB: 9.85% |
KO: 5.79% | PEP: 4.10% | AAPL: 2.60% |
Epoch: 5 | Train loss: 2.6332 | Train acc: 51.45% | Val loss: 2.7160 | Val acc: 47.44%
Learning rate: 0.000035

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, NVS, UPS,
BAC: WFC, JPM, C,
AAPL: 25.32% | AMZN: 12.66% | FB: 10.35% |
KO: 5.85% | PEP: 4.45% | AAPL: 2.74% |
Epoch: 6 | Train loss: 2.6108 | Train acc: 52.34% | Val loss: 2.7107 | Val acc: 47.58%
Learning rate: 0.000021

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, UPS, NVS,
BAC: WFC, JPM, C,
AAPL: 25.04% | AMZN: 13.23% | FB: 9.95% |
KO: 5.79% | PEP: 4.57% | AAPL: 2.60% |
Epoch: 7 | Train loss: 2.5929 | Train acc: 52.87% | Val loss: 2.7091 | Val acc: 48.32%
Learning rate: 0.000010

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, UPS, NVS,
BAC: WFC, JPM, C,
AAPL: 24.72% | AMZN: 13.41% | FB: 10.24% |
KO: 5.72% | PEP: 4.55% | AAPL: 2.56% |
Epoch: 8 | Train loss: 2.5805 | Train acc: 53.45% | Val loss: 2.7073 | Val acc: 48.35%
Learning rate: 0.000003

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, UPS, NVS,
BAC: WFC, JPM, C,
AAPL: 24.68% | AMZN: 13.20% | FB: 10.26% |
KO: 5.75% | PEP: 4.55% | AAPL: 2.62% |
Epoch: 9 | Train loss: 2.5744 | Train acc: 53.68% | Val loss: 2.7061 | Val acc: 48.29%
Learning rate: 0.000100

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, UPS, UTX,
BAC: WFC, JPM, C,
AAPL: 25.09% | AMZN: 11.68% | FB: 10.93% |
KO: 5.89% | PEP: 4.96% | AAPL: 2.95% |
Epoch: 10 | Train loss: 2.6053 | Train acc: 52.25% | Val loss: 2.7058 | Val acc: 48.52%
Learning rate: 0.000099

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, UPS, UTX,
BAC: WFC, JPM, C,
AAPL: 25.90% | AMZN: 11.98% | FB: 11.92% |
KO: 6.20% | PEP: 4.90% | AAPL: 2.87% |
Epoch: 11 | Train loss: 2.5879 | Train acc: 53.03% | Val loss: 2.6966 | Val acc: 48.53%
Learning rate: 0.000098

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, UPS, UTX,
BAC: WFC, JPM, C,
AAPL: 27.06% | AMZN: 11.35% | FB: 10.81% |
KO: 6.53% | PEP: 4.52% | AAPL: 2.82% |
Epoch: 12 | Train loss: 2.5709 | Train acc: 53.46% | Val loss: 2.6954 | Val acc: 48.90%
Learning rate: 0.000095

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, UPS, UTX,
BAC: WFC, JPM, C,
AAPL: 27.46% | FB: 12.59% | AMZN: 9.83% |
KO: 5.90% | PEP: 4.74% | AAPL: 2.98% |
Epoch: 13 | Train loss: 2.5558 | Train acc: 54.11% | Val loss: 2.6891 | Val acc: 48.70%
Learning rate: 0.000091

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, UPS, UTX,
BAC: WFC, JPM, C,
AAPL: 25.92% | FB: 12.09% | AMZN: 11.56% |
KO: 6.08% | PEP: 4.70% | AAPL: 3.21% |
Epoch: 14 | Train loss: 2.5406 | Train acc: 54.36% | Val loss: 2.6861 | Val acc: 48.86%
Learning rate: 0.000086

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 27.66% | FB: 11.66% | AMZN: 10.92% |
KO: 5.94% | PEP: 5.27% | DIS: 3.00% |
Epoch: 15 | Train loss: 2.5278 | Train acc: 54.86% | Val loss: 2.6839 | Val acc: 48.42%
Learning rate: 0.000080

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 28.47% | FB: 11.56% | AMZN: 9.87% |
KO: 5.95% | PEP: 5.43% | DIS: 3.14% |
Epoch: 16 | Train loss: 2.5173 | Train acc: 55.34% | Val loss: 2.6894 | Val acc: 49.39%
Learning rate: 0.000073

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 27.92% | FB: 11.90% | AMZN: 10.48% |
KO: 5.75% | PEP: 5.23% | DIS: 3.08% |
Epoch: 17 | Train loss: 2.5057 | Train acc: 55.74% | Val loss: 2.6842 | Val acc: 49.07%
Learning rate: 0.000066

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 28.06% | FB: 12.47% | AMZN: 9.42% |
KO: 6.06% | PEP: 5.31% | DIS: 2.89% |
Epoch: 18 | Train loss: 2.4966 | Train acc: 56.20% | Val loss: 2.6836 | Val acc: 49.33%
Learning rate: 0.000058

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 30.20% | FB: 11.53% | AMZN: 10.04% |
KO: 5.80% | PEP: 5.10% | AAPL: 2.88% |
Epoch: 19 | Train loss: 2.4864 | Train acc: 56.65% | Val loss: 2.6820 | Val acc: 49.38%
Learning rate: 0.000051

AAPL: FB, AMZN, GOOG,
FB: GOOG, AAPL, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 29.21% | FB: 10.79% | AMZN: 9.96% |
KO: 6.07% | PEP: 5.30% | DIS: 2.90% |
Epoch: 20 | Train loss: 2.4781 | Train acc: 56.94% | Val loss: 2.6841 | Val acc: 49.52%
Learning rate: 0.000043

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 31.21% | FB: 11.69% | AMZN: 9.86% |
KO: 6.08% | PEP: 5.29% | AAPL: 3.14% |
Epoch: 21 | Train loss: 2.4715 | Train acc: 57.24% | Val loss: 2.6810 | Val acc: 49.23%
Learning rate: 0.000035

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 30.92% | FB: 11.40% | AMZN: 9.32% |
KO: 6.03% | PEP: 5.32% | AAPL: 3.00% |
Epoch: 22 | Train loss: 2.4652 | Train acc: 57.44% | Val loss: 2.6826 | Val acc: 49.38%
Learning rate: 0.000028

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 30.54% | FB: 11.86% | AMZN: 9.89% |
KO: 6.09% | PEP: 5.20% | DIS: 3.15% |
Epoch: 23 | Train loss: 2.4592 | Train acc: 57.79% | Val loss: 2.6824 | Val acc: 49.33%
Learning rate: 0.000021

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 31.15% | FB: 11.76% | AMZN: 8.87% |
KO: 6.09% | PEP: 5.16% | DIS: 3.06% |
Epoch: 24 | Train loss: 2.4533 | Train acc: 58.13% | Val loss: 2.6811 | Val acc: 49.34%
Learning rate: 0.000015

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 30.51% | FB: 12.03% | AMZN: 9.75% |
KO: 6.02% | PEP: 5.20% | AAPL: 3.08% |
Epoch: 25 | Train loss: 2.4486 | Train acc: 58.33% | Val loss: 2.6804 | Val acc: 49.13%
Learning rate: 0.000010

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 30.84% | FB: 11.74% | AMZN: 9.36% |
KO: 6.03% | PEP: 5.29% | DIS: 3.06% |
Epoch: 26 | Train loss: 2.4460 | Train acc: 58.44% | Val loss: 2.6829 | Val acc: 49.35%
Learning rate: 0.000006

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 31.01% | FB: 11.84% | AMZN: 9.37% |
KO: 5.98% | PEP: 5.30% | DIS: 3.06% |
Epoch: 27 | Train loss: 2.4424 | Train acc: 58.57% | Val loss: 2.6828 | Val acc: 49.34%
Learning rate: 0.000003

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 31.13% | FB: 11.59% | AMZN: 9.29% |
KO: 5.98% | PEP: 5.26% | DIS: 3.06% |
Epoch: 28 | Train loss: 2.4405 | Train acc: 58.66% | Val loss: 2.6828 | Val acc: 49.26%
Learning rate: 0.000002

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 31.21% | FB: 11.66% | AMZN: 9.25% |
KO: 6.00% | PEP: 5.27% | AAPL: 3.06% |
Epoch: 29 | Train loss: 2.4392 | Train acc: 58.82% | Val loss: 2.6825 | Val acc: 49.26%
Learning rate: 0.000100

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 30.67% | FB: 11.71% | AMZN: 9.39% |
KO: 5.73% | PEP: 5.07% | AAPL: 3.42% |
Epoch: 30 | Train loss: 2.4765 | Train acc: 56.95% | Val loss: 2.6854 | Val acc: 48.86%
Learning rate: 0.000100

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 31.22% | FB: 11.63% | AMZN: 10.18% |
PEP: 5.73% | KO: 5.65% | AAPL: 2.99% |
Epoch: 31 | Train loss: 2.4735 | Train acc: 56.96% | Val loss: 2.6790 | Val acc: 48.84%
Learning rate: 0.000099

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 28.71% | AMZN: 13.29% | FB: 11.39% |
KO: 6.15% | PEP: 5.02% | AAPL: 3.14% |
Epoch: 32 | Train loss: 2.4694 | Train acc: 56.95% | Val loss: 2.6825 | Val acc: 49.23%
Learning rate: 0.000099

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 32.25% | FB: 10.77% | AMZN: 9.81% |
KO: 5.84% | PEP: 5.11% | AAPL: 3.39% |
Epoch: 33 | Train loss: 2.4639 | Train acc: 57.32% | Val loss: 2.6786 | Val acc: 48.77%
Learning rate: 0.000098

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,
AAPL: 31.68% | FB: 11.22% | AMZN: 8.91% |
KO: 6.00% | PEP: 5.57% | AAPL: 3.37% |
Epoch: 34 | Train loss: 2.4572 | Train acc: 57.50% | Val loss: 2.6808 | Val acc: 49.33%
Learning rate: 0.000096

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 31.42% | FB: 10.75% | AMZN: 10.28% |
KO: 5.64% | PEP: 4.81% | AAPL: 3.18% |
Epoch: 35 | Train loss: 2.4523 | Train acc: 57.60% | Val loss: 2.6828 | Val acc: 49.02%
Learning rate: 0.000095

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 31.17% | FB: 11.94% | AMZN: 10.68% |
KO: 5.55% | PEP: 5.45% | MCD: 3.10% |
Epoch: 36 | Train loss: 2.4461 | Train acc: 57.87% | Val loss: 2.6827 | Val acc: 49.18%
Learning rate: 0.000093

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, UPS,
BAC: WFC, JPM, C,
AAPL: 31.97% | AMZN: 11.27% | FB: 10.69% |
KO: 6.13% | PEP: 5.39% | MCD: 3.17% |
Epoch: 37 | Train loss: 2.4416 | Train acc: 57.94% | Val loss: 2.6849 | Val acc: 49.14%
Learning rate: 0.000091

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,
AAPL: 31.64% | FB: 11.36% | AMZN: 11.00% |
KO: 5.86% | PEP: 4.95% | AAPL: 3.31% |
Epoch: 38 | Train loss: 2.4348 | Train acc: 58.30% | Val loss: 2.6796 | Val acc: 48.62%
Learning rate: 0.000088

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, PCLN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,
AAPL: 33.40% | FB: 11.90% | AMZN: 9.16% |
KO: 5.57% | PEP: 5.06% | DIS: 3.22% |
Epoch: 39 | Train loss: 2.4310 | Train acc: 58.36% | Val loss: 2.6871 | Val acc: 49.15%
Learning rate: 0.000086

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,
AAPL: 32.28% | FB: 11.62% | AMZN: 9.84% |
KO: 5.81% | PEP: 5.20% | DIS: 3.20% |
Epoch: 40 | Train loss: 2.4254 | Train acc: 58.72% | Val loss: 2.6825 | Val acc: 48.91%
Learning rate: 0.000083

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,
AAPL: 34.03% | FB: 11.51% | AMZN: 9.21% |
KO: 6.09% | PEP: 5.08% | MCD: 3.17% |
Epoch: 41 | Train loss: 2.4210 | Train acc: 58.79% | Val loss: 2.6809 | Val acc: 48.85%
Learning rate: 0.000080

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,
AAPL: 32.70% | FB: 12.08% | AMZN: 10.28% |
KO: 5.61% | PEP: 4.98% | DIS: 3.18% |
Epoch: 42 | Train loss: 2.4140 | Train acc: 59.05% | Val loss: 2.6764 | Val acc: 48.28%
Learning rate: 0.000076

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, PCLN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,
AAPL: 33.64% | FB: 11.89% | AMZN: 9.53% |
KO: 5.13% | PEP: 4.92% | MCD: 3.20% |
Epoch: 43 | Train loss: 2.4085 | Train acc: 59.34% | Val loss: 2.6800 | Val acc: 48.05%
Learning rate: 0.000073

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,
AAPL: 33.59% | FB: 11.99% | AMZN: 9.45% |
KO: 6.32% | PEP: 5.29% | MCD: 3.22% |
Epoch: 44 | Train loss: 2.4061 | Train acc: 59.37% | Val loss: 2.6811 | Val acc: 48.88%
Learning rate: 0.000069

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,
AAPL: 33.49% | FB: 11.74% | AMZN: 9.71% |
KO: 5.49% | PEP: 5.16% | MCD: 3.18% |
Epoch: 45 | Train loss: 2.4005 | Train acc: 59.60% | Val loss: 2.6861 | Val acc: 48.69%
Learning rate: 0.000066

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,
AAPL: 33.68% | FB: 12.14% | AMZN: 9.21% |
KO: 5.66% | PEP: 5.01% | DIS: 3.08% |
Epoch: 46 | Train loss: 2.3967 | Train acc: 59.81% | Val loss: 2.6832 | Val acc: 48.58%
Learning rate: 0.000062

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,
AAPL: 31.11% | FB: 11.96% | AMZN: 11.24% |
KO: 5.58% | PEP: 5.01% | MCD: 3.12% |
Epoch: 47 | Train loss: 2.3914 | Train acc: 59.85% | Val loss: 2.6898 | Val acc: 48.89%
Learning rate: 0.000058

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,
AAPL: 31.27% | FB: 12.83% | AMZN: 10.68% |
KO: 5.76% | PEP: 5.27% | MCD: 3.10% |
Epoch: 48 | Train loss: 2.3868 | Train acc: 60.13% | Val loss: 2.6808 | Val acc: 48.23%
Learning rate: 0.000054

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,
AAPL: 31.24% | FB: 12.43% | AMZN: 11.51% |
KO: 5.62% | PEP: 5.32% | MCD: 3.31% |
Epoch: 49 | Train loss: 2.3858 | Train acc: 60.22% | Val loss: 2.6839 | Val acc: 48.53%
Learning rate: 0.000051

### Analyze Embedding Quality

In [111]:
# torch.save(model.state_dict(), "model.pth")
# torch.save(model.state_dict(), "best_model.pth")
torch.manual_seed(42)
torch.cuda.manual_seed(42)

model = StockIdentification(
    num_stocks=num_stocks,
    embd_size=128,
    hidden_size=64,
    vocab_size=vocab_size
)

model.load_state_dict(torch.load(dataset_dir / "best_model.pth", map_location=device))

In [28]:
stock_cosine_similarities(model)
print()
tweet_embedding_quality(model)

AAPL: FB, AMZN, GOOG,
FB: AAPL, GOOG, AMZN,
BA: LMT, UTX, HON,
BAC: WFC, JPM, C,

AAPL: 31.43% | FB: 11.55% | AMZN: 9.67% |
KO: 5.49% | PEP: 5.01% | MCD: 3.37% |

## Global Trend with Attention

The global trend vector is generated by weighting the price features of stocks based on their popularity in tweets.

The average of all tweet embeddings at day $t$ ($g_t$) is used as the query vector.

The key vector is $h_s$, and the value vector is $x_{st}$.

$$
o_t = \sum_{s' \in S} \alpha_{st} x_{st}\;\; \text {where} \;\; \alpha_{st} = \frac{\exp(g_t^\top h_s)}{\sum_{s' \in S} \exp(g_t^\top h_{s'})}


$$

In [ ]:
all_tweet_embs = []

for d in tqdm(range(num_dates)):
    tweets = X_by_date[d].to(device)
    indices = mask_indices_by_date[d].to(device)

    _, h_e, _ = model(tweets, indices)
    all_tweet_embs.append(h_e)

g_t = torch.stack([torch.mean(h_e, dim=0) for h_e in all_tweet_embs])
g_t.shape # (num_days, 2*hidden_size)

100%|██████████| 696/696 [03:40<00:00,  3.15it/s]

In [ ]:
# a_st (num_days, num_stocks) @ x_st (num_days, num_stocks, num_features) -> o_t (num_days, num_features)
# g_t (num_days, 2*hidden_size)  @ h_s.T (2*hidden_size, num_stocks) -> a_st (num_days, num_stocks)

In [207]:
h_s = model.stock_embd.weight

attn_scores = torch.matmul(g_t, h_s.T)

weights = F.softmax(attn_scores, dim=-1)
weights.shape

torch.Size([696, 87])

In [209]:
X_st.shape

torch.Size([651, 87, 11])